apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"monitoring.coreos.com/v1","kind":"ServiceMonitor","metadata":{"annotations":{},"labels":{"release":"prometheus-community"},"name":"falcosidekick","namespace":"monitoring"},"spec":{"endpoints":[{"interval":"10s","path":"/metrics","port":"http","scheme":"http"}],"namespaceSelector":{"matchNames":["falcosidekick"]},"selector":{"matchLabels":{"app":"falcosidekick"}}}}
  labels:
    app: falcosidekick
    release: prometheus-community
  name: falcosidekick
  namespace: monitoring
spec:
  endpoints:
  - interval: 10s
    path: /metrics
    port: http
    scheme: http
  namespaceSelector:
    matchNames:
    - falcosidekick
  selector:
    matchLabels:
      app: falcosidekick
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"monitoring.coreos.com/v1","kind":"PrometheusRule","metadata":{"annotations":{},"labels":{"app":"falcosidekick","release":"prometheus-community"},"name":"falco-alerts","namespace":"monitoring"},"spec":{"groups":[{"name":"falco","rules":[{"alert":"FalcoWarningPriority","annotations":{"description":"Falco detected a warning event in {{ $labels.k8s_namespace_name }}/{{ $labels.k8s_pod_name }}","summary":"Falco warning event detected"},"expr":"falcosecurity_falcosidekick_falco_events_total{priority_raw=\"Warning\"} \u003e 0","for":"1m","labels":{"severity":"warning"}},{"alert":"FalcoErrorPriority","annotations":{"description":"Falco detected an error event in {{ $labels.k8s_namespace_name }}/{{ $labels.k8s_pod_name }}","summary":"Falco error event detected"},"expr":"falcosecurity_falcosidekick_falco_events_total{priority_raw=\"Error\"} \u003e 0","for":"1m","labels":{"severity":"error"}}]}]}}
  labels:
    app: falcosidekick
    release: prometheus-community
  name: falco-alerts
  namespace: monitoring
spec:
  groups:
  - name: falco
    rules:
    - alert: FalcoWarningPriority
      annotations:
        description: Falco detected a warning event in {{ $labels.k8s_namespace_name
          }}/{{ $labels.k8s_pod_name }}
        summary: Falco warning event detected
      expr: falcosecurity_falcosidekick_falco_events_total{priority_raw="Warning"}
        > 0
      for: 1m
      labels:
        severity: warning
    - alert: FalcoErrorPriority
      annotations:
        description: Falco detected an error event in {{ $labels.k8s_namespace_name
          }}/{{ $labels.k8s_pod_name }}
        summary: Falco error event detected
      expr: falcosecurity_falcosidekick_falco_events_total{priority_raw="Error"} >
        0
      for: 1m
      labels:
        severity: error
